//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public string LoggingLevel { get; set; }
        public string ErrorType { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateTimeUTC { get; set; }
    }
}
